name: Center for Spatial Inclusion
brand: Centre for Spatial Inclusion
description: Designing cities for everybody.
keyword:
url: http://kimadactyl.github.io/csi-site/
email: s.white@mmu.ac.uk
twitter: TheMSArch
github: kimadactyl
author: Kim Foale
year: 2016
markdown: kramdown
exclude:
  - node_modules
collections:
  projects:
    output: true
    permalink: /projects/:title/
defaults:
  -
    scope:
      type: "projects"
    values:
      layout: "project"
      preview: "./preview.jpg"
