name: Center for Spatial Inclusion
brand: Centre for Spatial Inclusion
description: Designing cities for everybody.
keyword:
url: http://kimadactyl.github.io/csi-site/
email: s.white@mmu.ac.uk
twitter: TheMSArch
github: kimadactyl
author: Kim Foale
year: 2016
markdown: kramdown
destination: docs
baseurl: /csi-site
exclude:
  - node_modules
collections:
  work:
    output: true
    permalink: /work/:title/
  theme:
    output: true
    permalink: /theme/:title/
defaults:
  -
    scope:
      type: "work"
    values:
      layout: "work"
      preview: "./preview.jpg"
  -
    scope:
      type: "theme"
    values:
      layout: "theme"
